== Icinga Oracle Plugin ==

A Java/JDBC plugin for monitoring Oracle Databases using Icinga.  

Currently supported operation:
* Monitor the general connectivity to the database, ensuring the TNS Listener is available
* Monitor usage on all tablespaces with universal warning and critical % thresholds
* Monitor usage on a single tablespace with specific warning and critical % thresholds
* Monitor the total count of all active sessions in the database
* Monitor the total count of active session for a single user

=== Requirements: ===
* Apache Maven version 3
* JDK6 and higher
* Oracle 11g

=== Usage: ===
The current plugin supports following options.

[source,bash]
----

usage: check_oracle [-C <arg>] [-D] [-d] -H <arg> [-h] -I <arg> -P <arg>
       -p <arg> [-s <arg> | -t <arg> | -tns]   -u <arg> [-W <arg>]
 -C <arg>                    The critical threshold you want to set
 -D                          Enable output of Nagios performance data
 -d,--debug                  Option to enable debugging [true|false]
 -H,--host <arg>             The database hostname to connect to
 -h,--help                   Print help for this application
 -I,--instance <arg>         The database instance name
 -P,--port <arg>             The database listener port
 -p,--password <arg>         The password for the user
 -s,--sessions <arg>         The username for which session count to
                             check, pass ALL to count all sessions
 -t,--tablespace <arg>       The tablespace to check, pass ALL for all
                             tablespaces
 -tns,--tns-listener-check   Check that a connection can be made to the
                             database.
 -u,--user <arg>             The username you want to login as
 -W <arg>                    The warning threshold you want to set

----

=== Installation ===

Clone the project and build it using:

  mvn clean package
  
Copy target/check_oracle.jar and ./check_oracle to your icinga plugins directory.

See the examples below on defining CheckCommand, Service and Host objects for each type of check.

=== Check TNS Listener Usage: ===

=== Database Session Usage: ===

=== User Sessions Usage: ===

=== All Tablespaces Usage: ===

=== Single Tablespace Usage: ===


=== Licensing and Copyright: ===

The project is licensed under the http://www.apache.org/licenses/LICENSE-2.0[Apache License, Version 2.0]

=== Acknowledgement ===

This project was inspired and built upon the original work here: https://github.com/aparnachaudhary/nagios-plugin-oracle[aparnachaudhary/nagios-oracle-plugin]