== Nagios Oracle Plugin ==

This project provides a JDBC based plugin to monitor Oracle database using Nagios. The plugin currently supports monitoring of tablespace usage percentage and active session count for user.

=== Requirements: ===
* Apache Maven version 3
* JDK6 and higher
* Oracle 11g

=== Usage: ===
The current plugin supports following options.

[source,bash]
----

Aparna$ java -jar nagios-plugin-oracle.jar -h
usage: java -jar nagios-plugin-oracle.jar -C <arg> [-D] [-d] -H <arg> [-h]
       -I <arg> -P <arg> -p <arg> [-s <arg>] [-t <arg>] -u <arg> -W <arg>
 -C <arg>                The critical threshold you want to set
 -D                      Enable output of Nagios performance data
 -d,--debug              Option to enable debugging [true|false]
 -H,--host <arg>         The database hostname to connect to
 -h,--help               Print help for this application
 -I,--instance <arg>     The database instance name
 -P,--port <arg>         The database listener port
 -p,--password <arg>     The password for the user
 -s,--sessions <arg>     The username for which session count to check
 -t,--tablespace <arg>   The tablespace to check
 -u,--user <arg>         The username you want to login as
 -W <arg>                The warning threshold you want to set

----

=== Check Tablespace Usage: ===

This section provides example configuration for checking percent tablespace usage.

==== Installation: ====

Edit your commands.cfg and add the following

 define command {
    command_name    check_tablespace
    command_line    $USER1$/nagios-plugin-oracle.jar -H $HOSTADDRESS$ -P $ARG1$ -I $ARG2$ -u $ARG3$ -p $ARG4$ -t $ARG5$ -W $ARG6$ -C $ARG7$
 }

(add -D to the command if you want to add perfdata to the output)
Then you can reference it like the following.

==== Usage: ====

===== Check TEMP Tablespace Usage =====

The option allows you to monitor the percent tablespace usage for the given tablespace name e.g. +TEMP+.

 define service {
    use                     generic-service
    hostgroup_name          Oracle Servers
    service_description     TEMP_TABLESPACE_USAGE
    check_command           check_tablespace!1521!XE!admin!password!TEMP!10!20
 }

===== Check USERS Tablespace Usage =====

The option allows you to monitor the percent tablespace usage for +USERS+ tablespace. The +WARNING+ threshold is set to 60% and +CRITICAL+ threshold is set to 80%

 define service {
    use                     generic-service
    hostgroup_name          Oracle Servers
    service_description     USERS_TABLESPACE_USAGE
    check_command           check_tablespace!1521!XE!admin!password!USERS!60!80
 }

=== Licensing and Copyright: ===

The project is licensed under the http://www.apache.org/licenses/LICENSE-2.0[Apache License, Version 2.0]
